USE V_League

CREATE TABLE CAUTHU(
	MACT NUMERIC PRIMARY KEY IDENTITY(1,1),
	HOTEN NVARCHAR(100) NOT NULL,
	VITRI NVARCHAR(20) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MACLB VARCHAR(5) NOT NULL,
	MAQG VARCHAR(5) NOT NULL,
	SO INT NOT NULL
)

CREATE TABLE QUOCGIA(
	MAQG VARCHAR(5) PRIMARY KEY,
	TENQG NVARCHAR(60) NOT NULL
)

CREATE TABLE CAULACBO(
	MACLB VARCHAR(5) PRIMARY KEY,
	TENCLB NVARCHAR(100) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	MATINH VARCHAR(5) NOT NULL
)

CREATE TABLE TINH(
	MATINH VARCHAR(5) PRIMARY KEY,
	TENTINH NVARCHAR(100) NOT NULL
)

CREATE TABLE SANVD(
	MASAN VARCHAR(5) PRIMARY KEY,
	TENSAN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200)
)

CREATE TABLE HUANLUYENVIEN(
	MAHLV VARCHAR(5) PRIMARY KEY,
	TENHLV NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	DIENTHOAI NVARCHAR(20),
	MAQG VARCHAR(5) NOT NULL
)

CREATE TABLE HLV_CLB(
	MAHLV VARCHAR(5),
	MACLB VARCHAR(5),
	VAITRO NVARCHAR(100) NOT NULL,
	PRIMARY KEY (MAHLV, MACLB)
)

CREATE TABLE TRANDAU(
	MATRAN NUMERIC PRIMARY KEY IDENTITY(1,1),
	NAM INT NOT NULL,
	VONG INT NOT NULL,
	NGAYTD DATETIME NOT NULL,
	MACLB1 VARCHAR(5) NOT NULL,
	MACLB2 VARCHAR(5) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	KETQUA VARCHAR(5) NOT NULL
)

CREATE TABLE BANGXH(
	MACLB VARCHAR(5) NOT NULL,
	NAM INT NOT NULL,
	VONG INT NOT NULL,
	SOTRAN INT NOT NULL,
	THANG INT NOT NULL,
	HOA INT NOT NULL,
	THUA INT NOT NULL,
	HIEUSO VARCHAR(5) NOT NULL,
	DIEM INT NOT NULL,
	HANG INT NOT NULL,
	PRIMARY KEY (MACLB, NAM, VONG)
)

